name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to Glitch project
        run: |
          curl -X POST https://api.glitch.com/project/githubImport \
            -u "kRxZykRxZy:Hi1992Hi1992" \
            -H "Content-Type: application/json" \
            -d '{"projectId":"3f142cc3-7525-4672-a122-e8813799b9d3","repo":"https://github.com/kRxZykRxZy/ScratchyFetch"}'
