# .github/workflows/node-run.yml
name: Run Server Temporarily

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: |
          cd src
          npm install
          node npm/server.js
